### ISSUE TITLE
JavaClient: Client continually attempts to create connections when network is down

### ISSUE THREAD

**Issue by mwm-twx** [Azure/azure-event-hubs#179]
Disabling the network on a system while a EventHubClient and PartitionReceiver are running eventually (20 minutes) leads to repeated `UnresolvedAddressException`s:
```java
2016-06-30 10:27:28.506-0400 [L: WARN] [O: s.trace] [T: Thread-14] UnHandled exception while processing events in reactor:
java.nio.channels.UnresolvedAddressException
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:304)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:273)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:341)
java.lang.Thread.run(Thread.java:745)Cause: null
sun.nio.ch.Net.checkAddress(Net.java:101)
sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)
org.apache.qpid.proton.reactor.impl.IOHandler.handleBound(IOHandler.java:111)
org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:328)
org.apache.qpid.proton.engine.BaseHandler.onConnectionBound(BaseHandler.java:58)
org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:131)
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:304)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:273)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:341)
java.lang.Thread.run(Thread.java:745)
```

These errors cause the library to attempt creation of new reactors, quickly exhausting the available file handles and leading to `IOException`s:
```java
2016-06-30 10:27:36.087-0400 [L: WARN] [O: s.trace] [T: Thread-4058] UnHandled exception while processing events in reactor:
org.apache.qpid.proton.reactor.impl.ReactorInternalException: java.io.IOException: Too many open files
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:304)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:273)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:341)
java.lang.Thread.run(Thread.java:745)Cause: java.io.IOException: Too many open files
org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:344)
org.apache.qpid.proton.engine.BaseHandler.onReactorInit(BaseHandler.java:86)
org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:209)
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:304)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:273)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:341)
java.lang.Thread.run(Thread.java:745)
```

Though the error is different, the handling of it leaves this issue very similar to #170.

Setup:
* azure-event-hubs version 0.7.1
* Hub with two partitions
* Two `EventHubClient`s, each with a single `PartitionReceiver`
* Attempting synchronous reads, no writes
* No traffic on the hub at all

**Comment by SreeramGarlapati** [comment]
Can you please try version 0.7.7 & confirm if this is gone...

**Comment by mwm-twx** [comment]
I still see the same behavior under 0.7.7.

**Comment by SreeramGarlapati** [comment]
When n/w is down - I believe continually trying to connect & bubbling up the error to the user is the right behavior. However, we should cleanup all system resources after every attempt to reconnect.

In this regard - can you verify if you are still experiencing `java.io.IOException: Too many open files` with our latest version (`0.8.0`).

#242 - fixes the issue where the underlying network outage error doesn't bubble up to the user.

**Comment by SreeramGarlapati** [comment]
we just released `0.8.1` - can you verify this..

**Comment by sjkwak** [comment]
@mwm-twx  - can you please let us know if you still see high resource usage with the latest version? It is expected behavior to keep retrying but it shouldn't cause resource consumption issue.

**Comment by mwm-twx** [comment]
With 0.8.1, I don't see the "too many open files" error and there is no excessive memory usage.

@SreeramGarlapati, I still see the "UnHandled exception while processing events in reactor" log and the error never bubbles-up to user-code; is that expected?

**Comment by SreeramGarlapati** [comment]
UnHandled exceptions in the reactor stack could be generic - while, this specific error - `java.nio.channels.UnresolvedAddressException`  is expected in this situation - the occurrence of UnHandled exception should be rare in general..

The principle we tried to stick to is that Random UnHandled exceptions happening on the Reactor thread shouldn't bubble-up to the user-code unless:
1. its a permanent error
2. its a transient error & retrying (applying the `ConnectionStringBuilder.RetryPolicy` doesn't help

**Comment by Sshubb** [comment]
> Hi Sreeram,
> I am facing the same exception in 0.8,2 version as well. It is causing exception while creating client:

`Sep 16, 2016 1:52:51 PM com.microsoft.azure.servicebus.MessagingFactory$RunReactor run
WARNING: UnHandled exception while processing events in reactor:
java.lang.IllegalArgumentException
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:277)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:332)
java.lang.Thread.run(Thread.java:745)Cause: null
java.nio.Buffer.position(Buffer.java:244)
org.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper.pop(SimpleSslTransportWrapper.java:411)
org.apache.qpid.proton.engine.impl.ssl.SslImpl$UnsecureClientAwareTransportWrapper.pop(SslImpl.java:185)
org.apache.qpid.proton.engine.impl.TransportImpl.pop(TransportImpl.java:1476)
org.apache.qpid.proton.reactor.impl.SelectorImpl.select(SelectorImpl.java:145)
org.apache.qpid.proton.reactor.impl.IOHandler.handleQuiesced(IOHandler.java:57)
org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:381)
org.apache.qpid.proton.engine.BaseHandler.onReactorQuiesced(BaseHandler.java:87)
org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:206)
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:277)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:332)
java.lang.Thread.run(Thread.java:745)
Sep 16, 2016 1:52:51 PM com.cognizant.iotworkbench.Channel.CatChannel sendData
SEVERE: null
java.util.concurrent.ExecutionException: com.microsoft.azure.servicebus.ServiceBusException: java.lang.IllegalArgumentException, TrackingId: d1b4531f-9ca4-4abc-9e40-9d3e5304f51c, at: 2016-09-16T13:52:51.510+05:30[Asia/Calcutta]
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1887)
	at com.cognizant.iotworkbench.Channel.CatChannel.sendData(CatChannel.java:34)
	at com.cognizant.iotworkbench.Channel.CatChannel.BroadcastData(CatChannel.java:101)
	at com.cognizant.iotworkbench.Channel.ChannelBehavior.lambda$new$0(ChannelBehavior.java:33)
	at com.cognizant.iotworkbench.Channel.ChannelBehavior$$Lambda$50/7600556.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.microsoft.azure.servicebus.ServiceBusException: java.lang.IllegalArgumentException, TrackingId: d1b4531f-9ca4-4abc-9e40-9d3e5304f51c, at: 2016-09-16T13:52:51.510+05:30[Asia/Calcutta]
	at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:357)
	... 1 more
Caused by: java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at org.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper.pop(SimpleSslTransportWrapper.java:411)
	at org.apache.qpid.proton.engine.impl.ssl.SslImpl$UnsecureClientAwareTransportWrapper.pop(SslImpl.java:185)
	at org.apache.qpid.proton.engine.impl.TransportImpl.pop(TransportImpl.java:1476)
	at org.apache.qpid.proton.reactor.impl.SelectorImpl.select(SelectorImpl.java:145)
	at org.apache.qpid.proton.reactor.impl.IOHandler.handleQuiesced(IOHandler.java:57)
	at org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:381)
	at org.apache.qpid.proton.engine.BaseHandler.onReactorQuiesced(BaseHandler.java:87)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:206)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:277)
	at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:332)
	... 1 more
`
I even tried with 0.8.1 version as well.What is the possible solution for this??

**Comment by SreeramGarlapati** [comment]
@Sshubb 
Can you point me to the exception stack trace in this issue - similar to your stacktrace ? Sorry, I can't relate to any part of the stacktrace.

Is this same as #263 ? or do you see different symptoms ?

**Comment by SreeramGarlapati** [comment]
@Sshubb - please file a new issue - if this issue is still persistent - as this is an old & closed issue and it will be tricky to track our milestones..
